//---------------------------------------------------------------------------

#ifndef MainFormH
#define MainFormH
 #define WM_MYMESSAGE WM_USER+1
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <Buttons.hpp>
#include <pngimage.hpp>
#include <ExtCtrls.hpp>
#include "RzButton.hpp"
#include <ImgList.hpp>
#include "RzPanel.hpp"
#include <Menus.hpp>
#include <ADODB.hpp>
#include <DB.hpp>
#include <ActnList.hpp>
#include "IWBaseControl.hpp"
#include "IWBaseHTMLControl.hpp"
#include "IWControl.hpp"
#include "IWExtCtrls.hpp"
#include "IWVCLBaseControl.hpp"
#include "RzStatus.hpp"
#include <ComCtrls.hpp>
#include <ToolWin.hpp>
//---------------------------------------------------------------------------

class TfrmMain : public TForm
{
__published:	// IDE-managed Components
	TImageList *ImageList1;
	TPanel *pancg;
	TRzToolButton *RzToolButton2;
	TImage *imagebj;
	TImage *Image2;
	TImageList *ImageList2;
	TRzToolButton *RzToolButton1;
	TRzToolButton *RzToolButton3;
	TRzToolButton *RzToolButton4;
	TImageList *ImageList3;
	TPanel *panps;
	TImage *Image7;
	TRzToolButton *RzToolButton5;
	TRzToolButton *RzToolButton6;
	TRzToolButton *RzToolButton7;
	TPanel *panfh;
	TImage *Image1;
	TRzToolButton *RzToolButton8;
	TRzToolButton *RzToolButton9;
	TRzToolButton *RzToolButton10;
	TPanel *panls;
	TImage *Image4;
	TRzToolButton *RzToolButton11;
	TRzToolButton *RzToolButton12;
	TRzToolButton *RzToolButton24;
	TPanel *pankc;
	TRzToolButton *RzToolButton25;
	TRzToolButton *RzToolButton26;
	TRzToolButton *RzToolButton27;
	TRzToolButton *RzToolButton28;
	TRzToolButton *RzToolButton29;
	TImageList *ImageList4;
	TImageList *ImageList5;
	TPanel *pankh;
	TRzToolButton *RzToolButton30;
	TRzToolButton *RzToolButton31;
	TRzToolButton *RzToolButton32;
	TRzToolButton *RzToolButton33;
	TRzToolButton *RzToolButton34;
	TRzToolButton *RzToolButton35;
	TPanel *pancx;
	TRzToolButton *RzToolButton36;
	TRzToolButton *RzToolButton37;
	TRzToolButton *RzToolButton38;
	TRzToolButton *RzToolButton39;
	TRzToolButton *RzToolButton40;
	TRzToolButton *RzToolButton41;
	TRzToolButton *RzToolButton42;
	TRzToolButton *RzToolButton43;
	TImage *Image5;
	TImage *Image6;
	TPanel *Panel2;
	TRzToolButton *RzToolButton56;
	TRzToolButton *RzToolButton57;
	TRzToolButton *RzToolButton58;
	TRzToolButton *RzToolButton59;
	TRzToolButton *RzToolButton60;
	TRzToolButton *RzToolButton61;
	TRzToolButton *RzToolButton62;
	TRzToolButton *RzToolButton63;
	TRzToolButton *RzToolButton64;
	TRzToolButton *RzToolButton65;
	TRzToolButton *RzToolButton66;
	TPanel *pancw;
	TRzToolButton *RzToolButton44;
	TRzToolButton *RzToolButton13;
	TRzToolButton *RzToolButton14;
	TRzToolButton *RzToolButton15;
	TRzToolButton *RzToolButton16;
	TRzToolButton *RzToolButton17;
	TRzToolButton *RzToolButton18;
	TRzToolButton *RzToolButton19;
	TRzToolButton *RzToolButton20;
	TRzToolButton *RzToolButton21;
	TRzToolButton *RzToolButton22;
	TRzToolButton *RzToolButton23;
	TImage *Image8;
	TImage *Image9;
	TImage *Image10;
	TImage *Image11;
	TLabel *Label1;
	TLabel *Label2;
	TLabel *Label3;
	TLabel *Label4;
	TActionList *ActionList;
	TAction *rlogin;
	TAction *quit;
	TAction *StogeSet;
	TAction *retailPrint;
	TAction *Printtitle;
	TAction *peishong;
	TAction *OrderControl;
	TAction *StockControl;
	TAction *storagecontrol;
	TAction *SaleControl;
	TAction *RetailControl;
	TAction *PeiShongControl;
	TAction *logSearch;
	TAction *specialPassWord;
	TAction *DanHaoDisplay;
	TAction *retailclassPromotion;
	TAction *Retailbuy;
	TAction *MemberoneProduct;
	TAction *Memberjifen;
	TAction *SaleOneProduct;
	TAction *SaleAddPoint;
	TAction *SaleNowbackDot;
	TAction *Procure;
	TAction *storage;
	TAction *storageback;
	TAction *sqPeisong;
	TAction *zdpeisong;
	TAction *Retail;
	TAction *retailback;
	TAction *POSjiaoban;
	TAction *Order;
	TAction *Sale;
	TAction *financestart;
	TAction *supplierduizhang;
	TAction *Supplierjieshuan;
	TAction *SupplierjieShuanSearch;
	TAction *ClientfinanceStart;
	TAction *ClientWanglaiduizhang;
	TAction *ClientJieShuan;
	TAction *BreedManage;
	TAction *catalogMake;
	TAction *pressmanage;
	TAction *breedType;
	TAction *LocalManage;
	TAction *memberclass;
	TAction *StorageInfo;
	TAction *SupplierClass;
	TAction *ClientClass;
	TAction *kucunyujing;
	TAction *shikupandian;
	TAction *storageLocaladjust;
	TAction *onestorageNumberadjust;
	TAction *Storagealarm;
	TAction *OperatorManage;
	TAction *rolemanage;
	TAction *PowerSet;
	TAction *SupplierInfo;
	TAction *ClientInfo;
	TAction *Stuffinfo;
	TAction *MemberInfo;
	TAction *Memberchongzhi;
	TAction *MemberchongziSearch;
	TAction *StorageSearch;
	TAction *OrderSearch;
	TAction *stocksearch;
	TAction *rikusearch;
	TAction *salesearch;
	TAction *posretailsearch;
	TAction *storagechecksearch;
	TAction *peishongsearch;
	TAction *manual;
	TAction *systemupdate;
	TAction *about;
	TAction *yihutotal;
	TAction *yingfudetail;
	TAction *yingshouhuizhong;
	TAction *yingshoudetail;
	TAction *Clientjieshuansearch;
	TAction *saleback;
	TAction *netorder;
	TAction *clientjieduanjiesuan;
	TAction *supplierjieduanjiesuan;
	TAction *jingxiaochunfenxie;
	TAction *weidongkuchun;
	TAction *retailhuizhongfengxie;
	TAction *yefupaihangbang;
	TAction *paihangfenxi;
	TAction *saletimehuizhong;
	TAction *saletongjireport;
	TAction *renwu;
	TAction *wengdang;
	TAction *jiaoliu;
	TAction *peisong;
	TAction *Clientbijiao;
	TAction *Supplierbijiao;
	TAction *tongjibaobiao;
	TAction *dangrijz;
	TAction *Jxcbijiao;
	TAction *wangshangOrder;
	TAction *catalogneworrec;
	TAction *Ordershenhei;
	TAction *CaigouOrder;
	TAction *bookfenfa;
	TAction *fahuorate;
	TAction *daohuorate;
	TAction *caigoutixing;
	TAction *ordertixing;
	TAction *Orderaskbook;
	TAction *siglebook;
	TAction *siglebookfenfa;
	TAction *saletongqi;
	TAction *rukutongqi;
	TAction *qikanguanli;
	TAction *StorToStor;
	TAction *Memberadddot;
	TAction *StockAlarmControl;
	TAction *Mutibook;
	TAction *ZNreturn;
	TPanel *Panel1;
	TRzToolButton *tbcg;
	TRzToolButton *tbps;
	TRzToolButton *tbfh;
	TRzToolButton *tbls;
	TRzToolButton *tbkc;
	TRzToolButton *tbkh;
	TRzToolButton *tbcx;
	TRzToolButton *tbcw;
	TIWImage *IWImage1;
	TPopupMenu *PMfile;
	TMenuItem *N1;
	TMenuItem *N2;
	TLabel *stgname;
	TPopupMenu *PMsystem;
	TMenuItem *N117;
	TMenuItem *N119;
	TMenuItem *N138;
	TMenuItem *N120;
	TMenuItem *N121;
	TMenuItem *N122;
	TMenuItem *N123;
	TMenuItem *N124;
	TMenuItem *N125;
	TMenuItem *N126;
	TMenuItem *N127;
	TMenuItem *N128;
	TMenuItem *N129;
	TMenuItem *N130;
	TMenuItem *N131;
	TMenuItem *N132;
	TMenuItem *N133;
	TMenuItem *N69;
	TMenuItem *N139;
	TMenuItem *N134;
	TPopupMenu *PMbasicData;
	TMenuItem *N3;
	TMenuItem *N4;
	TMenuItem *N10;
	TMenuItem *N5;
	TMenuItem *N6;
	TMenuItem *N7;
	TMenuItem *N11;
	TMenuItem *N8;
	TMenuItem *N9;
	TPopupMenu *PMcatalog;
	TMenuItem *N15;
	TMenuItem *N16;
	TMenuItem *N35;
	TMenuItem *N43;
	TMenuItem *N73;
	TPopupMenu *PMwlclient;
	TMenuItem *N17;
	TMenuItem *N18;
	TPopupMenu *PMprocure;
	TMenuItem *N48;
	TMenuItem *N162;
	TMenuItem *N36;
	TMenuItem *N41;
	TMenuItem *N163;
	TMenuItem *N75;
	TPopupMenu *PMpeisong;
	TMenuItem *MenuItem3;
	TMenuItem *MenuItem4;
	TPopupMenu *PMsale;
	TMenuItem *MenuItem1;
	TMenuItem *MenuItem2;
	TMenuItem *N12;
	TMenuItem *POS1;
	TMenuItem *N13;
	TMenuItem *N14;
	TMenuItem *N19;
	TPopupMenu *PMstack;
	TMenuItem *MenuItem5;
	TMenuItem *MenuItem6;
	TMenuItem *MenuItem7;
	TMenuItem *MenuItem8;
	TMenuItem *MenuItem9;
	TMenuItem *MenuItem10;
	TMenuItem *MenuItem11;
	TMenuItem *N20;
	TMenuItem *N21;
	TMenuItem *N22;
	TMenuItem *N23;
	TMenuItem *N24;
	TMenuItem *N25;
	TMenuItem *N26;
	TMenuItem *N31;
	TMenuItem *N32;
	TMenuItem *N38;
	TMenuItem *N33;
	TMenuItem *N34;
	TMenuItem *N40;
	TMenuItem *N42;
	TMenuItem *N44;
	TMenuItem *N63;
	TMenuItem *N64;
	TPopupMenu *PManalysis;
	TMenuItem *MenuItem12;
	TMenuItem *MenuItem13;
	TMenuItem *MenuItem15;
	TMenuItem *MenuItem16;
	TMenuItem *MenuItem18;
	TMenuItem *N27;
	TMenuItem *N28;
	TMenuItem *N29;
	TPopupMenu *PMhelp;
	TMenuItem *MenuItem14;
	TMenuItem *MenuItem17;
	TMenuItem *MenuItem19;
	TLabel *lbversion;
	TRzGlyphStatus *g1;
	TRzGlyphStatus *g2;
	TRzGlyphStatus *g3;
	TRzGlyphStatus *g4;
	TRzGlyphStatus *g5;
	TLabel *lbmore;
	TLabel *msg1;
	TLabel *msg2;
	TLabel *msg3;
	TLabel *msg4;
	TLabel *msg5;
	TADOStoredProc *adosp;
	TRzGlyphStatus *g6;
	TLabel *msg6;
	TImage *Image12;
	TImage *Image13;
	TImage *Image14;
	TImage *Image15;
	TLabel *lbtitle;
	TImage *imageui;
	TTimer *Timer1;
	TMenuItem *N30;
	TMenuItem *N37;
	TMenuItem *N39;
	TMenuItem *N45;
	TAction *wenjuguanli;
	TMenuItem *N46;
	TAction *clientadddot;
	TMenuItem *N47;
	TMenuItem *N49;
	TMenuItem *N50;
	TMenuItem *N51;
	TMenuItem *N52;
	TMenuItem *N53;
	TMenuItem *N54;
	TMenuItem *N55;
	TMenuItem *N56;
	TMenuItem *N57;
	TMenuItem *N58;
	TMenuItem *N59;
	TMenuItem *N60;
	TMainMenu *MainMenu1;
	TMenuItem *N110;
	TMenuItem *N210;
	TMenuItem *N310;
	TMenuItem *N410;
	TMenuItem *N510;
	TMenuItem *N61;
	TRzToolbar *MainToolBar;
	TRzToolButton *maitoolbutton;
	TRzToolButton *RzToolButton46;
	TRzToolButton *RzToolButton47;
	TRzToolButton *RzToolButton48;
	TRzToolButton *RzToolButton49;
	TRzToolButton *RzToolButton50;
	TRzToolButton *RzToolButton51;
	TRzToolButton *RzToolButton52;
	TRzToolButton *RzToolButton53;
	TRzToolButton *RzToolButton54;
	TRzToolButton *RzToolButton55;
	TRzToolButton *RzToolButton45;
	TMenuItem *N62;
	TMenuItem *N65;
	TMenuItem *N66;
	TMenuItem *N67;
	TMenuItem *N68;
	TMenuItem *N70;
	TMenuItem *N71;
	TMenuItem *N72;
	void __fastcall imageuiMouseDown(TObject *Sender, TMouseButton Button, TShiftState Shift,
          int X, int Y);
	void __fastcall SpeedButton1Click(TObject *Sender);
	void __fastcall imagecg1Click(TObject *Sender);
	void __fastcall imagecw1Click(TObject *Sender);
	void __fastcall imagecx1Click(TObject *Sender);
	void __fastcall imageps1Click(TObject *Sender);
	void __fastcall imagefh1Click(TObject *Sender);
	void __fastcall imagels1Click(TObject *Sender);
	void __fastcall imagekc1Click(TObject *Sender);
	void __fastcall imagekh1Click(TObject *Sender);
	void __fastcall tbcgClick(TObject *Sender);
	void __fastcall tbpsClick(TObject *Sender);
	void __fastcall tbfhClick(TObject *Sender);
	void __fastcall tblsClick(TObject *Sender);
	void __fastcall tbkcClick(TObject *Sender);
	void __fastcall tbkhClick(TObject *Sender);
	void __fastcall tbcxClick(TObject *Sender);
	void __fastcall tbcwClick(TObject *Sender);
	void __fastcall FormShow(TObject *Sender);
	void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
	void __fastcall ProcureExecute(TObject *Sender);
	void __fastcall storageExecute(TObject *Sender);
	void __fastcall storagebackExecute(TObject *Sender);
	void __fastcall ZNreturnExecute(TObject *Sender);
	void __fastcall sqPeisongExecute(TObject *Sender);
	void __fastcall zdpeisongExecute(TObject *Sender);
	void __fastcall RetailExecute(TObject *Sender);
	void __fastcall retailbackExecute(TObject *Sender);
	void __fastcall POSjiaobanExecute(TObject *Sender);
	void __fastcall OrderExecute(TObject *Sender);
	void __fastcall SaleExecute(TObject *Sender);
	void __fastcall salebackExecute(TObject *Sender);
	void __fastcall StorageSearchExecute(TObject *Sender);
	void __fastcall OrderSearchExecute(TObject *Sender);
	void __fastcall stocksearchExecute(TObject *Sender);
	void __fastcall rikusearchExecute(TObject *Sender);
	void __fastcall salesearchExecute(TObject *Sender);
	void __fastcall posretailsearchExecute(TObject *Sender);
	void __fastcall storagechecksearchExecute(TObject *Sender);
	void __fastcall peishongsearchExecute(TObject *Sender);
	void __fastcall financestartExecute(TObject *Sender);
	void __fastcall ClientfinanceStartExecute(TObject *Sender);
	void __fastcall supplierduizhangExecute(TObject *Sender);
	void __fastcall ClientWanglaiduizhangExecute(TObject *Sender);
	void __fastcall yihutotalExecute(TObject *Sender);
	void __fastcall yingfudetailExecute(TObject *Sender);
	void __fastcall yingshouhuizhongExecute(TObject *Sender);
	void __fastcall yingshoudetailExecute(TObject *Sender);
	void __fastcall SupplierjieShuanSearchExecute(TObject *Sender);
	void __fastcall ClientjieshuansearchExecute(TObject *Sender);
	void __fastcall SupplierjieshuanExecute(TObject *Sender);
	void __fastcall ClientJieShuanExecute(TObject *Sender);
	void __fastcall SupplierInfoExecute(TObject *Sender);
	void __fastcall ClientInfoExecute(TObject *Sender);
	void __fastcall StuffinfoExecute(TObject *Sender);
	void __fastcall MemberInfoExecute(TObject *Sender);
	void __fastcall MemberchongzhiExecute(TObject *Sender);
	void __fastcall MemberchongziSearchExecute(TObject *Sender);
	void __fastcall StoragealarmExecute(TObject *Sender);
	void __fastcall storageLocaladjustExecute(TObject *Sender);
	void __fastcall onestorageNumberadjustExecute(TObject *Sender);
	void __fastcall shikupandianExecute(TObject *Sender);
	void __fastcall kucunyujingExecute(TObject *Sender);
	void __fastcall rloginExecute(TObject *Sender);
	void __fastcall quitExecute(TObject *Sender);
	void __fastcall RzToolButton56Click(TObject *Sender);
	void __fastcall StogeSetExecute(TObject *Sender);
	void __fastcall DanHaoDisplayExecute(TObject *Sender);
	void __fastcall RzToolButton57Click(TObject *Sender);
	void __fastcall retailPrintExecute(TObject *Sender);
	void __fastcall PrinttitleExecute(TObject *Sender);
	void __fastcall logSearchExecute(TObject *Sender);
	void __fastcall OrderControlExecute(TObject *Sender);
	void __fastcall StockControlExecute(TObject *Sender);
	void __fastcall storagecontrolExecute(TObject *Sender);
	void __fastcall SaleControlExecute(TObject *Sender);
	void __fastcall RetailControlExecute(TObject *Sender);
	void __fastcall PeiShongControlExecute(TObject *Sender);
	void __fastcall StockAlarmControlExecute(TObject *Sender);
	void __fastcall pressmanageExecute(TObject *Sender);
	void __fastcall breedTypeExecute(TObject *Sender);
	void __fastcall LocalManageExecute(TObject *Sender);
	void __fastcall memberclassExecute(TObject *Sender);
	void __fastcall StorageInfoExecute(TObject *Sender);
	void __fastcall SupplierClassExecute(TObject *Sender);
	void __fastcall ClientClassExecute(TObject *Sender);
	void __fastcall RzToolButton58Click(TObject *Sender);
	void __fastcall BreedManageExecute(TObject *Sender);
	void __fastcall catalogMakeExecute(TObject *Sender);
	void __fastcall catalogneworrecExecute(TObject *Sender);
	void __fastcall qikanguanliExecute(TObject *Sender);
	void __fastcall MutibookExecute(TObject *Sender);
	void __fastcall RzToolButton59Click(TObject *Sender);
	void __fastcall RzToolButton60Click(TObject *Sender);
	void __fastcall RzToolButton61Click(TObject *Sender);
	void __fastcall RzToolButton62Click(TObject *Sender);
	void __fastcall RzToolButton63Click(TObject *Sender);
	void __fastcall RzToolButton64Click(TObject *Sender);
	void __fastcall OperatorManageExecute(TObject *Sender);
	void __fastcall rolemanageExecute(TObject *Sender);
	void __fastcall PowerSetExecute(TObject *Sender);
	void __fastcall StorToStorExecute(TObject *Sender);
	void __fastcall specialPassWordExecute(TObject *Sender);
	void __fastcall retailclassPromotionExecute(TObject *Sender);
	void __fastcall RetailbuyExecute(TObject *Sender);
	void __fastcall MemberoneProductExecute(TObject *Sender);
	void __fastcall MemberjifenExecute(TObject *Sender);
	void __fastcall MemberadddotExecute(TObject *Sender);
	void __fastcall SaleOneProductExecute(TObject *Sender);
	void __fastcall SaleAddPointExecute(TObject *Sender);
	void __fastcall SaleNowbackDotExecute(TObject *Sender);
	void __fastcall jingxiaochunfenxieExecute(TObject *Sender);
	void __fastcall saletimehuizhongExecute(TObject *Sender);
	void __fastcall yefupaihangbangExecute(TObject *Sender);
	void __fastcall retailhuizhongfengxieExecute(TObject *Sender);
	void __fastcall clientjieduanjiesuanExecute(TObject *Sender);
	void __fastcall supplierjieduanjiesuanExecute(TObject *Sender);
	void __fastcall RzToolButton65Click(TObject *Sender);
	void __fastcall siglebookExecute(TObject *Sender);
	void __fastcall paihangfenxiExecute(TObject *Sender);
	void __fastcall manualExecute(TObject *Sender);
	void __fastcall systemupdateExecute(TObject *Sender);
	void __fastcall aboutExecute(TObject *Sender);
	void __fastcall RzToolButton66Click(TObject *Sender);
	void __fastcall msg1Click(TObject *Sender);
	void __fastcall lbmoreClick(TObject *Sender);
	void __fastcall Image10Click(TObject *Sender);
	void __fastcall Image11Click(TObject *Sender);
	void __fastcall wenjuguanliExecute(TObject *Sender);
	void __fastcall clientadddotExecute(TObject *Sender);
	void __fastcall Image9Click(TObject *Sender);
	void __fastcall N49Click(TObject *Sender);
	void __fastcall Timer1Timer(TObject *Sender);
	void __fastcall N52Click(TObject *Sender);
	void __fastcall N54Click(TObject *Sender);
	void __fastcall N56Click(TObject *Sender);
	void __fastcall N57Click(TObject *Sender);
	void __fastcall N59Click(TObject *Sender);
	void __fastcall N60Click(TObject *Sender);
	void __fastcall maitoolbuttonClick(TObject *Sender);
	void __fastcall N62Click(TObject *Sender);
	void __fastcall N66Click(TObject *Sender);
	void __fastcall Image8Click(TObject *Sender);
	void __fastcall N67Click(TObject *Sender);
	void __fastcall N71Click(TObject *Sender);
	void __fastcall N70Click(TObject *Sender);
	void __fastcall N72Click(TObject *Sender);

private:	// User declarations
        TStringList *PowerList;
        void LoadMyMessage();
        TStringList *MessageInfo;
        TStringList *MessagePic;
        void LanuchOrder(AnsiString type1,AnsiString ID,AnsiString DanHao,AnsiString IDstr);

        BEGIN_MESSAGE_MAP
        VCL_MESSAGE_HANDLER(WM_MYMESSAGE, TMessage, ToolBarShowOrNot)
       

        END_MESSAGE_MAP(TForm);
        void __fastcall ToolBarShowOrNot(TMessage &msg);
        void __fastcall MainClose(TMessage &msg);
        void DisVisable();

public:		// User declarations
	__fastcall TfrmMain(TComponent* Owner);
	void __fastcall ClientWndProc(TMessage&   Message);
	TFarProc NewClientWndProc;
	TFarProc OriginalClientWndProc;
	void GetPowerList(int UserID);
	BOOL CheckPower(String ModalName);
	void ShowNoPower();
	void TPclick(int tt);
        TADOConnection *Acon;
	int tag;
	int AUserID;
	int AStorageID;
	AnsiString AUserName;
	AnsiString AStorageName;
	bool AMaster;
	int jiaojie;
        AnsiString GetTitle();
        void InitDiffVersion();
        void InitQF();      //区分供应商或客户
        bool Qfclient;
        bool Qfsupplier;
        int version;
};
BOOL CALLBACK EnumChildWin(HWND hwndChild,LPARAM lParam);
//---------------------------------------------------------------------------
extern PACKAGE TfrmMain *frmMain;
//---------------------------------------------------------------------------
#endif
