//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <Buttons.hpp>
#include <pngimage.hpp>
#include <ExtCtrls.hpp>
#include "RzButton.hpp"
#include <ImgList.hpp>
#include "RzPanel.hpp"
#include <Menus.hpp>
#include <ADODB.hpp>
#include <DB.hpp>
#include <ActnList.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE-managed Components
	TImage *imageui;
	TImageList *ImageList1;
	TPanel *pancg;
	TRzToolButton *RzToolButton2;
	TImage *imagebj;
	TImage *Image2;
	TImageList *ImageList2;
	TRzToolButton *RzToolButton1;
	TRzToolButton *RzToolButton3;
	TRzToolButton *RzToolButton4;
	TImageList *ImageList3;
	TPanel *panps;
	TImage *Image7;
	TRzToolButton *RzToolButton5;
	TRzToolButton *RzToolButton6;
	TRzToolButton *RzToolButton7;
	TPanel *panfh;
	TImage *Image1;
	TRzToolButton *RzToolButton8;
	TRzToolButton *RzToolButton9;
	TRzToolButton *RzToolButton10;
	TImage *Image3;
	TPanel *panls;
	TImage *Image4;
	TRzToolButton *RzToolButton11;
	TRzToolButton *RzToolButton12;
	TRzToolButton *RzToolButton24;
	TPanel *pankc;
	TRzToolButton *RzToolButton25;
	TRzToolButton *RzToolButton26;
	TRzToolButton *RzToolButton27;
	TRzToolButton *RzToolButton28;
	TRzToolButton *RzToolButton29;
	TImageList *ImageList4;
	TImageList *ImageList5;
	TPanel *pankh;
	TRzToolButton *RzToolButton30;
	TRzToolButton *RzToolButton31;
	TRzToolButton *RzToolButton32;
	TRzToolButton *RzToolButton33;
	TRzToolButton *RzToolButton34;
	TRzToolButton *RzToolButton35;
	TPanel *pancx;
	TRzToolButton *RzToolButton36;
	TRzToolButton *RzToolButton37;
	TRzToolButton *RzToolButton38;
	TRzToolButton *RzToolButton39;
	TRzToolButton *RzToolButton40;
	TRzToolButton *RzToolButton41;
	TRzToolButton *RzToolButton42;
	TRzToolButton *RzToolButton43;
	TImage *Image5;
	TImage *Image6;
	TPanel *Panel2;
	TRzToolButton *RzToolButton56;
	TRzToolButton *RzToolButton57;
	TRzToolButton *RzToolButton58;
	TRzToolButton *RzToolButton59;
	TRzToolButton *RzToolButton60;
	TRzToolButton *RzToolButton61;
	TRzToolButton *RzToolButton62;
	TRzToolButton *RzToolButton63;
	TRzToolButton *RzToolButton64;
	TRzToolButton *RzToolButton65;
	TRzToolButton *RzToolButton66;
	TPanel *pancw;
	TRzToolButton *RzToolButton44;
	TADOConnection *Acon;
	TRzToolButton *RzToolButton13;
	TRzToolButton *RzToolButton14;
	TRzToolButton *RzToolButton15;
	TRzToolButton *RzToolButton16;
	TRzToolButton *RzToolButton17;
	TRzToolButton *RzToolButton18;
	TRzToolButton *RzToolButton19;
	TRzToolButton *RzToolButton20;
	TRzToolButton *RzToolButton21;
	TRzToolButton *RzToolButton22;
	TRzToolButton *RzToolButton23;
	TImage *Image8;
	TImage *Image9;
	TImage *Image10;
	TImage *Image11;
	TLabel *Label1;
	TLabel *Label2;
	TLabel *Label3;
	TLabel *Label4;
	TActionList *ActionList;
	TAction *rlogin;
	TAction *quit;
	TAction *StogeSet;
	TAction *retailPrint;
	TAction *Printtitle;
	TAction *SalePrint;
	TAction *caigouprint;
	TAction *orderPrint;
	TAction *peishong;
	TAction *OrderControl;
	TAction *StockControl;
	TAction *storagecontrol;
	TAction *SaleControl;
	TAction *RetailControl;
	TAction *PeiShongControl;
	TAction *B2BSet;
	TAction *logSearch;
	TAction *dbback;
	TAction *dbrestore;
	TAction *specialPassWord;
	TAction *DanHaoDisplay;
	TAction *retailclassPromotion;
	TAction *Retailbuy;
	TAction *MemberoneProduct;
	TAction *Memberjifen;
	TAction *SaleOneProduct;
	TAction *SaleAddPoint;
	TAction *SaleNowbackDot;
	TAction *SaleyearBackDot;
	TAction *Procure;
	TAction *storage;
	TAction *storageback;
	TAction *sqPeisong;
	TAction *zdpeisong;
	TAction *Retail;
	TAction *retailback;
	TAction *POSjiaoban;
	TAction *Order;
	TAction *Sale;
	TAction *financestart;
	TAction *supplierduizhang;
	TAction *Supplierjiduanfexie;
	TAction *Supplierjieshuan;
	TAction *SupplierjieShuanSearch;
	TAction *ClientfinanceStart;
	TAction *ClientWanglaiduizhang;
	TAction *Clientjieduanfexie;
	TAction *ClientJieShuan;
	TAction *Dangrijieshuan;
	TAction *BreedManage;
	TAction *catalogMake;
	TAction *pressmanage;
	TAction *breedType;
	TAction *LocalManage;
	TAction *memberclass;
	TAction *StorageInfo;
	TAction *SupplierClass;
	TAction *ClientClass;
	TAction *xuyipandian;
	TAction *shikupandian;
	TAction *storageLocaladjust;
	TAction *onestorageNumberadjust;
	TAction *Storagealarm;
	TAction *OperatorManage;
	TAction *rolemanage;
	TAction *PowerSet;
	TAction *SupplierInfo;
	TAction *ClientInfo;
	TAction *salermanage;
	TAction *creditManage;
	TAction *MemberInfo;
	TAction *Memberchongzhi;
	TAction *MemberchongziSearch;
	TAction *StorageSearch;
	TAction *OrderSearch;
	TAction *stocksearch;
	TAction *rikusearch;
	TAction *salesearch;
	TAction *posretailsearch;
	TAction *storagechecksearch;
	TAction *peishongsearch;
	TAction *manual;
	TAction *systemupdate;
	TAction *about;
	TAction *yihutotal;
	TAction *yingfudetail;
	TAction *yingshouhuizhong;
	TAction *yingshoudetail;
	TAction *Clientjieshuansearch;
	TAction *saleback;
	TAction *netorder;
	TAction *retailandback;
	TAction *saleandback;
	TAction *jingxiaochunfenxie;
	TAction *weidongkuchun;
	TAction *retailhuizhongfengxie;
	TAction *yefupaihangbang;
	TAction *changxiaobook;
	TAction *saletimehuizhong;
	TAction *saletongjireport;
	TAction *renwu;
	TAction *wengdang;
	TAction *jiaoliu;
	TAction *peisong;
	TAction *MyWork;
	TAction *Clientbijiao;
	TAction *Supplierbijiao;
	TAction *tongjibaobiao;
	TAction *FormView;
	TAction *dangrijz;
	TAction *Jxcbijiao;
	TAction *wangshangOrder;
	TAction *catalogneworrec;
	TAction *Ordershenhei;
	TAction *CaigouOrder;
	TAction *bookfenfa;
	TAction *fahuorate;
	TAction *daohuorate;
	TAction *Action1;
	TAction *caigoutixing;
	TAction *ordertixing;
	TAction *Orderaskbook;
	TAction *siglebook;
	TAction *siglebookfenfa;
	TAction *saletongqi;
	TAction *rukutongqi;
	TAction *qikanguanli;
	TAction *StorToStor;
	TAction *Setyjdiscount;
	TAction *Memberadddot;
	TAction *StockAlarmControl;
	TAction *Mutibook;
	TAction *ZNreturn;
	TPanel *Panel1;
	TRzToolButton *tbcg;
	TRzToolButton *tbps;
	TRzToolButton *tbfh;
	TRzToolButton *tbls;
	TRzToolButton *tbkc;
	TRzToolButton *tbkh;
	TRzToolButton *tbcx;
	TRzToolButton *tbcw;
	void __fastcall imageuiMouseDown(TObject *Sender, TMouseButton Button, TShiftState Shift,
          int X, int Y);
	void __fastcall SpeedButton1Click(TObject *Sender);
	void __fastcall imagecg1Click(TObject *Sender);
	void __fastcall imagecw1Click(TObject *Sender);
	void __fastcall imagecx1Click(TObject *Sender);
	void __fastcall imageps1Click(TObject *Sender);
	void __fastcall imagefh1Click(TObject *Sender);
	void __fastcall imagels1Click(TObject *Sender);
	void __fastcall imagekc1Click(TObject *Sender);
	void __fastcall imagekh1Click(TObject *Sender);
	void __fastcall tbcgClick(TObject *Sender);
	void __fastcall tbpsClick(TObject *Sender);
	void __fastcall tbfhClick(TObject *Sender);
	void __fastcall tblsClick(TObject *Sender);
	void __fastcall tbkcClick(TObject *Sender);
	void __fastcall tbkhClick(TObject *Sender);
	void __fastcall tbcxClick(TObject *Sender);
	void __fastcall tbcwClick(TObject *Sender);
	void __fastcall FormShow(TObject *Sender);
	void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
	void __fastcall ProcureExecute(TObject *Sender);
	void __fastcall storageExecute(TObject *Sender);
	void __fastcall storagebackExecute(TObject *Sender);
	void __fastcall ZNreturnExecute(TObject *Sender);
	void __fastcall sqPeisongExecute(TObject *Sender);
	void __fastcall zdpeisongExecute(TObject *Sender);
	void __fastcall RetailExecute(TObject *Sender);
	void __fastcall retailbackExecute(TObject *Sender);
	void __fastcall POSjiaobanExecute(TObject *Sender);
	void __fastcall OrderExecute(TObject *Sender);
	void __fastcall SaleExecute(TObject *Sender);
	void __fastcall salebackExecute(TObject *Sender);
	void __fastcall StorageSearchExecute(TObject *Sender);
	void __fastcall OrderSearchExecute(TObject *Sender);
	void __fastcall stocksearchExecute(TObject *Sender);
	void __fastcall rikusearchExecute(TObject *Sender);
	void __fastcall salesearchExecute(TObject *Sender);
	void __fastcall posretailsearchExecute(TObject *Sender);
	void __fastcall storagechecksearchExecute(TObject *Sender);
	void __fastcall peishongsearchExecute(TObject *Sender);
private:	// User declarations
	TStringList *PowerList;
public:		// User declarations
	__fastcall TForm1(TComponent* Owner);
	void __fastcall ClientWndProc(TMessage&   Message);
	TFarProc NewClientWndProc;
	TFarProc OriginalClientWndProc;
	void GetPowerList(int UserID);
	BOOL CheckPower(String ModalName);
	void ShowNoPower();
	void TPclick(int tt);
	int tag;
	int AUserID;
	int AStorageID;
	AnsiString AUserName;
	AnsiString AStorageName;
	bool AMaster;
	int jiaojie;
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
